// These aren't tracked as authoritative rules text
// They're optional and here for flavour.

// List from Ewen Cluney
export const FamilyNames = [
  "Autumn",
  "Waters",
  "Flint",
  "Ebony",
  "Gaston",
  "Pendragon",
  "Lockheart",
  "Lovelace",
  "Starshine",
  "Brooks",
  "Yuna",
  "Baxter",
  "Aimless"
]

// List from Ewen Cluney
export const GivenNames = [
  "Amy",
  "Yuki",
  "Sakura",
  "Hotaru",
  "Makoto",
  "Mika",
  "Jolene",
  "Ember",
  "Ashley",
  "Hazel",
  "Wanda",
  "Emilia",
  "Ada",
  "Kat",
  "Brooke",
  "Jill",
  "Beatrice"
]

export const ExampleThemes = [
  "Animals",
  "Blood",
  "Butterflies",
  "Chains",
  "Gems",
  "Earth",
  "Fate",
  "Feathers",
  "Toys",
  "Fire",
  "Flowers",
  "Force",
  "Fabric",
  "Gravity",
  "Tarot",
  "Healing",
  "Ice",
  "Leaves",
  "Light",
  "Lightning",
  "Love",
  "Magnetism",
  "Metal",
  "Moon",
  "Nothingness",
  "Rainbows",
  "Ribbons",
  "Sadness",
  "Shadow",
  "Stars",
  "Wounds",
  "Swords",
  "Time",
  "Water",
  "Wood",
  "Wind",
]

export const ExampleWeapons = [
  "Magic Wand",
  "Magic Staff",
  "Crystal Ball",
  "Tome",
  "Bell",
  "Shovel",
  "Handgun",
  "Sporting Equipment",
  "Shotgun",
  "Rifle",
  "Boots",
  "Musical Instrument",
  "Explosives",
  "Umbrella",
  "Gauntlets",
  "Dagger",
  "Bow",
  "Scarf",
  "Sword",
  "Shield",
  "Mace",
  "Frying Pan",
  "Axe",
  "Pole Arm",
  "Nunchucks",
  "Brick",
  "Ladle",
  "Mop",
  "Baseball Bat",
  "Tea Ware",
  "Flashlight",
  "Animal",
  "Ray Gun",
  "Cannon",
  "Microphone",
  "Ribbon",
]

export const ExampleCostume = [
  "Sailor Suit",
  "Sundress",
  "Skirt and Blazer",
  "Frilly Dress",
  "Jumper Dress",
  "Tokyo Fashion",
  "Harlequin",
  "Swashbuckler",
  "Ballet",
  "Circus",
  "Gymnast",
  "Idol Singer",
  "Wedding Dress",
  "Kimono",
  "Gothic Lolita",
  "Ball Gown",
  "Opera Diva",
  "Victorian Gown",
  "Fairy",
  "Witch",
  "Greek Heroine",
  "Professional Wrestler",
  "Red Riding Hood",
  "Sci-fi Heroine",
  "Nurse",
  "Maid",
  "Plague Doctor",
  "Bunny Suit",
  "Shinobi",
  "Nun",
  "Jumpsuit",
  "Armor",
  "Martial Arts",
  "Military Uniform",
  "Boy’s Uniform",
  "Winter Coat",
]

export const ExampleMagicalMark = [
  "A magic sigil appears somewhere on your body",
  "You no longer need to eat, and regular food makes you sick",
  "Your proportions are a little too perfect, your skin looks photoshopped, your eyes become just a little too large, and your hair looks like a cosplay wig",
  "You have tattoos that move and change on your skin",
  "Eigengrau - Your physical features are indescribable. This isn't noticeable unless someone actually tries",
  "You do not show up in photographs",
  "Your blood changes color",
  "When you are frightened, lights around you are extinguished.",
  "You lose one of your senses, but your magic compensates for this.",
  "When you cry, your tears flow like a running faucet.",
  "You can understand all languages, though you may not be able to speak them",
  "You gain an outlandish hairstyle that you can’t seem to get rid of",
  "Your voice becomes uncannily beautiful to everyone who hears it",
  "Electronic devices tend to malfunction around you",
  "Your body becomes slightly magnetic",
  "Your body smells of fresh blood. It is a coppery, unnerving smell",
  "Ordinary people have a hard time not paying attention to you",
  "Your body smells strongly of sweet candy",
  "You become cold-blooded",
  "One of your eyes becomes milky white. You can occasionally see spirits",
  "Your hair is made of transparent strands that display countless different colors when they catch the light",
  "You have heterochromia. Both your eyes are vivid, unnatural colors",
  "Your body is toxic to ordinary people. Your blood is poison, and physical contact with you gives people rashes",
  "You glow softly in the dark",
  "Occasionally you sleepwalk in your magical form",
  "When you get angry, your body temperature increases drastically. Hot enough to give 2nd degree burns to someone",
  "You gain a very acute sense of smell. About as good as a dog’s",
  "You can hear frequencies that humans can’t normally hear",
  "You develop an aversion to iron, silver, garlic, and rosemary. They make you dizzy and sick",
  "Animals are attracted to you. They tend to follow you around and act friendly",
  "Your body loses 50% of its mass. You are extremely light, though your outward appearance is unchanged",
  "Your body is dense. Your weight doubles, though your outward appearance is unchanged",
  "Your skin becomes hydrophobic",
  "When you are stressed, windows and fragile objects tend to spontaneously break",
  "Plants tend to wither and wilt when you touch them",
  "You no longer have a detectable heartbeat",
]